/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.PegawaiAdmin;
import db.Koneksi;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Fardan
 */
public class CekPembayaran extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CekPembayaran.class.getName());

    /**
     * Creates new form Login
     */
    public CekPembayaran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        namaPanel = new javax.swing.JPanel();
        namaField = new javax.swing.JTextField();
        alamatLabel = new javax.swing.JLabel();
        alamatPanel = new javax.swing.JPanel();
        alamatField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        paketLabel = new javax.swing.JLabel();
        paketPanel = new javax.swing.JPanel();
        paketField = new javax.swing.JTextField();
        studioLabel = new javax.swing.JLabel();
        studioPanel = new javax.swing.JPanel();
        studioField = new javax.swing.JTextField();
        jumlahLabel = new javax.swing.JLabel();
        jumlahPanel = new javax.swing.JPanel();
        jumlahField = new javax.swing.JTextField();
        jumlahOrangLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        totalHargaPanel = new javax.swing.JPanel();
        totalHargaField = new javax.swing.JTextField();
        idReservasiLabel = new javax.swing.JLabel();
        idReservasiPanel = new javax.swing.JPanel();
        idReservasiField = new javax.swing.JTextField();
        statusPembayaranLabel = new javax.swing.JLabel();
        statusPembayaranPanel = new javax.swing.JPanel();
        statusPembayaranField = new javax.swing.JTextField();
        terimaButton = new javax.swing.JButton();
        kembaliButton = new javax.swing.JButton();
        cariButton = new javax.swing.JButton();
        navbarPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setFont(new java.awt.Font("Retro Majestic Free", 0, 18)); // NOI18N
        logoLabel.setText("Bonas Studio");

        judulLabel.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        judulLabel.setText("Cek Pembayaran");

        namaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        namaLabel.setText("Nama Lengkap:");

        namaField.setEditable(false);
        namaField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout namaPanelLayout = new javax.swing.GroupLayout(namaPanel);
        namaPanel.setLayout(namaPanelLayout);
        namaPanelLayout.setHorizontalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        namaPanelLayout.setVerticalGroup(
            namaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namaPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        alamatLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        alamatLabel.setText("Alamat:");

        alamatField.setEditable(false);
        alamatField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        alamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alamatFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout alamatPanelLayout = new javax.swing.GroupLayout(alamatPanel);
        alamatPanel.setLayout(alamatPanelLayout);
        alamatPanelLayout.setHorizontalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        alamatPanelLayout.setVerticalGroup(
            alamatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alamatPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(alamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        emailLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        emailLabel.setText("Email:");

        emailField.setEditable(false);
        emailField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout emailPanelLayout = new javax.swing.GroupLayout(emailPanel);
        emailPanel.setLayout(emailPanelLayout);
        emailPanelLayout.setHorizontalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        emailPanelLayout.setVerticalGroup(
            emailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, emailPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        paketLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        paketLabel.setText("Paket:");

        paketField.setEditable(false);
        paketField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        paketField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        paketField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paketFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paketPanelLayout = new javax.swing.GroupLayout(paketPanel);
        paketPanel.setLayout(paketPanelLayout);
        paketPanelLayout.setHorizontalGroup(
            paketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paketField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        paketPanelLayout.setVerticalGroup(
            paketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paketPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(paketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        studioLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        studioLabel.setText("Studio:");

        studioField.setEditable(false);
        studioField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        studioField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studioFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studioPanelLayout = new javax.swing.GroupLayout(studioPanel);
        studioPanel.setLayout(studioPanelLayout);
        studioPanelLayout.setHorizontalGroup(
            studioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studioPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(studioField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        studioPanelLayout.setVerticalGroup(
            studioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studioPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(studioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jumlahLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jumlahLabel.setText("Jumlah:");

        jumlahField.setEditable(false);
        jumlahField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jumlahField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jumlahField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahFieldActionPerformed(evt);
            }
        });

        jumlahOrangLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jumlahOrangLabel.setText("orang");

        javax.swing.GroupLayout jumlahPanelLayout = new javax.swing.GroupLayout(jumlahPanel);
        jumlahPanel.setLayout(jumlahPanelLayout);
        jumlahPanelLayout.setHorizontalGroup(
            jumlahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jumlahOrangLabel)
                .addGap(10, 10, 10))
        );
        jumlahPanelLayout.setVerticalGroup(
            jumlahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jumlahPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahOrangLabel))
                .addGap(10, 10, 10))
        );

        totalHargaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalHargaLabel.setText("Total Harga:");

        totalHargaField.setEditable(false);
        totalHargaField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        totalHargaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout totalHargaPanelLayout = new javax.swing.GroupLayout(totalHargaPanel);
        totalHargaPanel.setLayout(totalHargaPanelLayout);
        totalHargaPanelLayout.setHorizontalGroup(
            totalHargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalHargaPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(totalHargaField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        totalHargaPanelLayout.setVerticalGroup(
            totalHargaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totalHargaPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(totalHargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        idReservasiLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        idReservasiLabel.setText("ID Reservasi:");

        idReservasiField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        idReservasiField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idReservasiFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout idReservasiPanelLayout = new javax.swing.GroupLayout(idReservasiPanel);
        idReservasiPanel.setLayout(idReservasiPanelLayout);
        idReservasiPanelLayout.setHorizontalGroup(
            idReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idReservasiPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(idReservasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        idReservasiPanelLayout.setVerticalGroup(
            idReservasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, idReservasiPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(idReservasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        statusPembayaranLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        statusPembayaranLabel.setText("Status Pembayaran:");

        statusPembayaranField.setEditable(false);
        statusPembayaranField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        statusPembayaranField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusPembayaranFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout statusPembayaranPanelLayout = new javax.swing.GroupLayout(statusPembayaranPanel);
        statusPembayaranPanel.setLayout(statusPembayaranPanelLayout);
        statusPembayaranPanelLayout.setHorizontalGroup(
            statusPembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPembayaranPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(statusPembayaranField, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        statusPembayaranPanelLayout.setVerticalGroup(
            statusPembayaranPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPembayaranPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(statusPembayaranField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        terimaButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        terimaButton.setText("Terima");
        terimaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terimaButtonActionPerformed(evt);
            }
        });

        kembaliButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        kembaliButton.setText("Kembali");
        kembaliButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliButtonActionPerformed(evt);
            }
        });

        cariButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        cariButton.setText("Cari");
        cariButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cariButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idReservasiLabel)
                            .addComponent(logoLabel)
                            .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailLabel)
                            .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(idReservasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cariButton, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bodyPanelLayout.createSequentialGroup()
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(alamatLabel)
                                    .addComponent(namaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(alamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paketLabel)
                                    .addComponent(paketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(studioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(studioLabel))
                                        .addGap(2, 2, 2)))))
                        .addGap(42, 42, 42)))
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPembayaranLabel)
                    .addComponent(statusPembayaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHargaLabel)
                    .addComponent(totalHargaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahLabel)
                    .addComponent(jumlahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(153, 153, 153))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(terimaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoLabel)
                .addGap(0, 0, 0)
                .addComponent(judulLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(idReservasiLabel)
                .addGap(3, 3, 3)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cariButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idReservasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(namaLabel)
                                .addGap(3, 3, 3)
                                .addComponent(namaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)
                                .addComponent(alamatLabel)
                                .addGap(3, 3, 3)
                                .addComponent(alamatPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(paketLabel)
                                .addGap(2, 2, 2)
                                .addComponent(paketPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(studioLabel)
                                .addGap(3, 3, 3)
                                .addComponent(studioPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addComponent(emailLabel)
                        .addGap(3, 3, 3)
                        .addComponent(emailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jumlahPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bodyPanelLayout.createSequentialGroup()
                                .addComponent(jumlahLabel)
                                .addGap(47, 47, 47)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(totalHargaLabel)
                        .addGap(2, 2, 2)
                        .addComponent(totalHargaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(statusPembayaranLabel)
                        .addGap(2, 2, 2)
                        .addComponent(statusPembayaranPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(61, 61, 61)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(terimaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembaliButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        navbarPanel.setBackground(new java.awt.Color(102, 102, 102));

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 763, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        model.User user = util.SessionManager.getInstance().getCurrentUser();

        if (user.getRole() == 0) { 
            new ui.Homepage.HomepageAdmin().setVisible(true);
        } else { 
            new ui.Homepage.HomepagePegawai().setVisible(true);
        }
        this.dispose();        
    }//GEN-LAST:event_backButtonActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void alamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alamatFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void paketFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paketFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paketFieldActionPerformed

    private void studioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studioFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studioFieldActionPerformed

    private void jumlahFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahFieldActionPerformed

    private void idReservasiFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idReservasiFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idReservasiFieldActionPerformed

    private void totalHargaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaFieldActionPerformed

    private void terimaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terimaButtonActionPerformed
        String idStr = idReservasiField.getText();
    
        try {
            Connection con = Koneksi.getConnection();
            String sql = "UPDATE reservation SET status_payment = 'PAID', is_done = 1 WHERE reservation_id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idStr);

            int updated = ps.executeUpdate();

            if (updated > 0) {
                JOptionPane.showMessageDialog(this, "Pembayaran Berhasil Dikonfirmasi!");
                statusPembayaranField.setText("PAID");
                terimaButton.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate status.");
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_terimaButtonActionPerformed

    private void cariButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariButtonActionPerformed
        String idStr = idReservasiField.getText().trim();
    
        if (idStr.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Masukkan ID Reservasi!");
            return;
        }

        try {
            java.sql.Connection con = db.Koneksi.getConnection();
            
            String sql = "SELECT r.*, u.full_name, u.address, u.email, " +
                         "p.name as paket_nama, p.price as harga_satuan, p.studio_id " +
                         "FROM reservation r " +
                         "JOIN user u ON r.user_id = u.user_id " +
                         "JOIN package p ON r.package_id = p.package_id " +
                         "WHERE r.reservation_id = ?";

            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, idStr);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                namaField.setText(rs.getString("full_name"));
                alamatField.setText(rs.getString("address"));
                emailField.setText(rs.getString("email"));
                paketField.setText(rs.getString("paket_nama"));

                studioField.setText(String.valueOf(rs.getInt("studio_id"))); 

                int total = rs.getInt("total_price");
                int hargaSatuan = rs.getInt("harga_satuan");
                int jumlahOrang = (hargaSatuan > 0) ? (total / hargaSatuan) : 0;

                jumlahField.setText(String.valueOf(jumlahOrang));
                totalHargaField.setText("Rp " + String.format("%,d", total));
                statusPembayaranField.setText(rs.getString("status_payment"));

                if ("PENDING".equalsIgnoreCase(rs.getString("status_payment"))) {
                    terimaButton.setEnabled(true);
                } else {
                    terimaButton.setEnabled(false);
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_cariButtonActionPerformed

    private void statusPembayaranFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusPembayaranFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusPembayaranFieldActionPerformed

    private void kembaliButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliButtonActionPerformed
        model.User user = util.SessionManager.getInstance().getCurrentUser();

        if (user.getRole() == 0) { 
            new ui.Homepage.HomepageAdmin().setVisible(true);
        } else { 
            new ui.Homepage.HomepagePegawai().setVisible(true);
        }
        this.dispose();   
    }//GEN-LAST:event_kembaliButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CekPembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CekPembayaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamatField;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JPanel alamatPanel;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JButton cariButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel emailPanel;
    private javax.swing.JTextField idReservasiField;
    private javax.swing.JLabel idReservasiLabel;
    private javax.swing.JPanel idReservasiPanel;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTextField jumlahField;
    private javax.swing.JLabel jumlahLabel;
    private javax.swing.JLabel jumlahOrangLabel;
    private javax.swing.JPanel jumlahPanel;
    private javax.swing.JButton kembaliButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JPanel namaPanel;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JTextField paketField;
    private javax.swing.JLabel paketLabel;
    private javax.swing.JPanel paketPanel;
    private javax.swing.JTextField statusPembayaranField;
    private javax.swing.JLabel statusPembayaranLabel;
    private javax.swing.JPanel statusPembayaranPanel;
    private javax.swing.JTextField studioField;
    private javax.swing.JLabel studioLabel;
    private javax.swing.JPanel studioPanel;
    private javax.swing.JButton terimaButton;
    private javax.swing.JTextField totalHargaField;
    private javax.swing.JLabel totalHargaLabel;
    private javax.swing.JPanel totalHargaPanel;
    // End of variables declaration//GEN-END:variables
}
