/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.PegawaiAdmin;

/**
 *
 * @author Fardan
 */
public class KelolaReservasiPopup extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KelolaReservasiPopup.class.getName());
    private int currentReservationId;
    /**
     * Creates new form Login
     */
    public KelolaReservasiPopup(int resId) {
        initComponents();
        this.currentReservationId = resId; 
        loadDetailData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupPanel = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        namaIsiLabel = new javax.swing.JLabel();
        alamatLabel = new javax.swing.JLabel();
        alamatIsiLabel = new javax.swing.JLabel();
        paketFotoLabel = new javax.swing.JLabel();
        paketFotoIsiLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        emailIsiLabel = new javax.swing.JLabel();
        studioLabel = new javax.swing.JLabel();
        studioIsiLabel = new javax.swing.JLabel();
        totalHargaLabel = new javax.swing.JLabel();
        totalHargaIsiLabel = new javax.swing.JLabel();
        jumlahLabel = new javax.swing.JLabel();
        jumlahIsiLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        namaLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        namaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLabel.setText("Nama:");

        namaIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        namaIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaIsiLabel.setText("1-10 orang");

        alamatLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        alamatLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamatLabel.setText("Alamat:");

        alamatIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        alamatIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alamatIsiLabel.setText("Alamat");

        paketFotoLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        paketFotoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paketFotoLabel.setText("Paket Foto:");

        paketFotoIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        paketFotoIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paketFotoIsiLabel.setText("1");

        emailLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        emailLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailLabel.setText("Email:");

        emailIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        emailIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        emailIsiLabel.setText("email@mail.com");

        studioLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        studioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studioLabel.setText("Studio:");

        studioIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        studioIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studioIsiLabel.setText("1");

        totalHargaLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        totalHargaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalHargaLabel.setText("Total Harga:");

        totalHargaIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        totalHargaIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalHargaIsiLabel.setText("Rp0");

        jumlahLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        jumlahLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahLabel.setText("Jumlah:");

        jumlahIsiLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jumlahIsiLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jumlahIsiLabel.setText("1 orang");

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/exit.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        hapusButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        okButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout popupPanelLayout = new javax.swing.GroupLayout(popupPanel);
        popupPanel.setLayout(popupPanelLayout);
        popupPanelLayout.setHorizontalGroup(
            popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(popupPanelLayout.createSequentialGroup()
                .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(namaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaIsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alamatLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alamatIsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(emailIsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paketFotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                    .addComponent(paketFotoIsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studioIsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlahLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jumlahIsiLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(popupPanelLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalHargaIsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalHargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        popupPanelLayout.setVerticalGroup(
            popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, popupPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(closeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(popupPanelLayout.createSequentialGroup()
                        .addComponent(namaLabel)
                        .addGap(0, 0, 0)
                        .addComponent(namaIsiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(alamatLabel)
                        .addGap(0, 0, 0)
                        .addComponent(alamatIsiLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailLabel)
                        .addGap(0, 0, 0)
                        .addComponent(emailIsiLabel))
                    .addGroup(popupPanelLayout.createSequentialGroup()
                        .addComponent(paketFotoLabel)
                        .addGap(0, 0, 0)
                        .addComponent(paketFotoIsiLabel)
                        .addGap(13, 13, 13)
                        .addComponent(studioLabel)
                        .addGap(0, 0, 0)
                        .addComponent(studioIsiLabel)
                        .addGap(13, 13, 13)
                        .addComponent(jumlahLabel)
                        .addGap(0, 0, 0)
                        .addComponent(jumlahIsiLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalHargaLabel)
                .addGap(0, 0, 0)
                .addComponent(totalHargaIsiLabel)
                .addGap(18, 18, 18)
                .addGroup(popupPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(popupPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(466, 387));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loadDetailData() {
        try {
            java.sql.Connection con = db.Koneksi.getConnection();
            String sql = "SELECT r.*, u.full_name, u.address, u.email, p.name as paket, p.studio_id " +
                         "FROM reservation r " +
                         "JOIN user u ON r.user_id = u.user_id " +
                         "JOIN package p ON r.package_id = p.package_id " +
                         "WHERE r.reservation_id = ?";

            java.sql.PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, currentReservationId);
            java.sql.ResultSet rs = ps.executeQuery();

            if (rs.next()) {
                namaIsiLabel.setText(rs.getString("full_name"));
                alamatIsiLabel.setText(rs.getString("address"));
                emailIsiLabel.setText(rs.getString("email"));
                paketFotoIsiLabel.setText(rs.getString("paket"));
                studioIsiLabel.setText("Studio " + rs.getInt("studio_id"));
                totalHargaIsiLabel.setText("Rp " + rs.getInt("total_price"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Hapus reservasi ini? (Status akan menjadi CANCELLED)", 
            "Konfirmasi Hapus", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            try {
                java.sql.Connection con = db.Koneksi.getConnection();
                String sql = "UPDATE reservation SET status_payment = 'CANCELLED' WHERE reservation_id = ?";
                java.sql.PreparedStatement ps = con.prepareStatement(sql);
                ps.setInt(1, currentReservationId);
                ps.executeUpdate();

                javax.swing.JOptionPane.showMessageDialog(this, "Reservasi Dibatalkan.");
                new ui.PegawaiAdmin.KelolaReservasi().setVisible(true);
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }        
    }//GEN-LAST:event_hapusButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        new ui.PegawaiAdmin.KelolaReservasi().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_closeButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        new ui.PegawaiAdmin.KelolaReservasi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KelolaReservasiPopup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KelolaReservasiPopup(0).setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alamatIsiLabel;
    private javax.swing.JLabel alamatLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel emailIsiLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jumlahIsiLabel;
    private javax.swing.JLabel jumlahLabel;
    private javax.swing.JLabel namaIsiLabel;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel paketFotoIsiLabel;
    private javax.swing.JLabel paketFotoLabel;
    private javax.swing.JPanel popupPanel;
    private javax.swing.JLabel studioIsiLabel;
    private javax.swing.JLabel studioLabel;
    private javax.swing.JLabel totalHargaIsiLabel;
    private javax.swing.JLabel totalHargaLabel;
    // End of variables declaration//GEN-END:variables
}
