/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.PegawaiAdmin;

/**
 *
 * @author Fardan
 */
public class LaporanKeuangan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName());

    /**
     * Creates new form Login
     */
    public LaporanKeuangan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        laporanTabbedPane = new javax.swing.JTabbedPane();
        harianPanel = new javax.swing.JPanel();
        harianScrollPane = new javax.swing.JScrollPane();
        harianTable = new javax.swing.JTable();
        tanggalHarianLabel = new javax.swing.JLabel();
        bulanHarianComboBox = new javax.swing.JComboBox<>();
        mingguanHarianComboBox = new javax.swing.JComboBox<>();
        tahunHarianComboBox = new javax.swing.JComboBox<>();
        mingguanPanel = new javax.swing.JPanel();
        mingguanScrollPane = new javax.swing.JScrollPane();
        mingguanTable = new javax.swing.JTable();
        tanggalMingguanLabel = new javax.swing.JLabel();
        bulanMingguanComboBox = new javax.swing.JComboBox<>();
        tahunMingguanComboBox = new javax.swing.JComboBox<>();
        bulananPanel = new javax.swing.JPanel();
        bulananScrollPane = new javax.swing.JScrollPane();
        bulananTable = new javax.swing.JTable();
        tanggalBulananLabel = new javax.swing.JLabel();
        tahunBulananComboBox = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        navbarPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setFont(new java.awt.Font("Retro Majestic Free", 0, 18)); // NOI18N
        logoLabel.setText("Bonas Studio");

        judulLabel.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        judulLabel.setText("Laporan Keuangan");

        harianTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        harianTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Hari", "Pendapatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        harianScrollPane.setViewportView(harianTable);

        tanggalHarianLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        tanggalHarianLabel.setText("Tanggal:");

        bulanHarianComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        bulanHarianComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        bulanHarianComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanHarianComboBoxActionPerformed(evt);
            }
        });

        mingguanHarianComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        mingguanHarianComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Minggu 1", "Minggu 2", "Minggu 3", "Minggu 4" }));
        mingguanHarianComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mingguanHarianComboBoxActionPerformed(evt);
            }
        });

        tahunHarianComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tahunHarianComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun" }));
        tahunHarianComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunHarianComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout harianPanelLayout = new javax.swing.GroupLayout(harianPanel);
        harianPanel.setLayout(harianPanelLayout);
        harianPanelLayout.setHorizontalGroup(
            harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(harianPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(harianPanelLayout.createSequentialGroup()
                        .addComponent(bulanHarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mingguanHarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tahunHarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggalHarianLabel))
                .addGap(12, 12, 12)
                .addComponent(harianScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        harianPanelLayout.setVerticalGroup(
            harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(harianPanelLayout.createSequentialGroup()
                .addGroup(harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(harianPanelLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(tanggalHarianLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(harianPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bulanHarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tahunHarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mingguanHarianComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(harianPanelLayout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(harianScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        laporanTabbedPane.addTab("Harian", harianPanel);

        mingguanTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        mingguanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Minggu", "Pendapatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mingguanScrollPane.setViewportView(mingguanTable);

        tanggalMingguanLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        tanggalMingguanLabel.setText("Tanggal:");

        bulanMingguanComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        bulanMingguanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        bulanMingguanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bulanMingguanComboBoxActionPerformed(evt);
            }
        });

        tahunMingguanComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tahunMingguanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun" }));
        tahunMingguanComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunMingguanComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mingguanPanelLayout = new javax.swing.GroupLayout(mingguanPanel);
        mingguanPanel.setLayout(mingguanPanelLayout);
        mingguanPanelLayout.setHorizontalGroup(
            mingguanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mingguanPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mingguanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tanggalMingguanLabel)
                    .addGroup(mingguanPanelLayout.createSequentialGroup()
                        .addComponent(bulanMingguanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tahunMingguanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addComponent(mingguanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mingguanPanelLayout.setVerticalGroup(
            mingguanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mingguanPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(tanggalMingguanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mingguanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulanMingguanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tahunMingguanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mingguanPanelLayout.createSequentialGroup()
                .addContainerGap(122, Short.MAX_VALUE)
                .addComponent(mingguanScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );

        laporanTabbedPane.addTab("Mingguan", mingguanPanel);

        bulananTable.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        bulananTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "No", "Bulan", "Pendapatan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bulananScrollPane.setViewportView(bulananTable);

        tanggalBulananLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        tanggalBulananLabel.setText("Tanggal:");

        tahunBulananComboBox.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        tahunBulananComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun" }));
        tahunBulananComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunBulananComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bulananPanelLayout = new javax.swing.GroupLayout(bulananPanel);
        bulananPanel.setLayout(bulananPanelLayout);
        bulananPanelLayout.setHorizontalGroup(
            bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bulananPanelLayout.createSequentialGroup()
                .addGroup(bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bulananPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tanggalBulananLabel)
                        .addGap(224, 224, 224))
                    .addGroup(bulananPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tahunBulananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bulananScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bulananPanelLayout.setVerticalGroup(
            bulananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bulananPanelLayout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(tanggalBulananLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tahunBulananComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bulananPanelLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(bulananScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        laporanTabbedPane.addTab("Bulanan", bulananPanel);

        okButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(laporanTabbedPane, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logoLabel)
                            .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoLabel)
                .addGap(0, 0, 0)
                .addComponent(judulLabel)
                .addGap(40, 40, 40)
                .addComponent(laporanTabbedPane)
                .addGap(18, 18, 18)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        navbarPanel.setBackground(new java.awt.Color(102, 102, 102));

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void bulanHarianComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanHarianComboBoxActionPerformed
        //        updateDayBox();
    }//GEN-LAST:event_bulanHarianComboBoxActionPerformed

    private void tahunHarianComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunHarianComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunHarianComboBoxActionPerformed

    private void mingguanHarianComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mingguanHarianComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mingguanHarianComboBoxActionPerformed

    private void bulanMingguanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bulanMingguanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bulanMingguanComboBoxActionPerformed

    private void tahunMingguanComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunMingguanComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunMingguanComboBoxActionPerformed

    private void tahunBulananComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunBulananComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunBulananComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaporanKeuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LaporanKeuangan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JComboBox<String> bulanHarianComboBox;
    private javax.swing.JComboBox<String> bulanMingguanComboBox;
    private javax.swing.JPanel bulananPanel;
    private javax.swing.JScrollPane bulananScrollPane;
    private javax.swing.JTable bulananTable;
    private javax.swing.JPanel harianPanel;
    private javax.swing.JScrollPane harianScrollPane;
    private javax.swing.JTable harianTable;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JTabbedPane laporanTabbedPane;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JComboBox<String> mingguanHarianComboBox;
    private javax.swing.JPanel mingguanPanel;
    private javax.swing.JScrollPane mingguanScrollPane;
    private javax.swing.JTable mingguanTable;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JButton okButton;
    private javax.swing.JComboBox<String> tahunBulananComboBox;
    private javax.swing.JComboBox<String> tahunHarianComboBox;
    private javax.swing.JComboBox<String> tahunMingguanComboBox;
    private javax.swing.JLabel tanggalBulananLabel;
    private javax.swing.JLabel tanggalHarianLabel;
    private javax.swing.JLabel tanggalMingguanLabel;
    // End of variables declaration//GEN-END:variables
}
