/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.User;

/**
 *
 * @author Fardan
 */
public class BuatReservasiBayar extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BuatReservasiBayar.class.getName());

    /**
     * Creates new form Login
     */
    public BuatReservasiBayar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bodyPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        judulLabel = new javax.swing.JLabel();
        isiLabel1 = new javax.swing.JLabel();
        isiLabel2 = new javax.swing.JLabel();
        totalBiayaLabel = new javax.swing.JLabel();
        totalBiayaIsiLabel = new javax.swing.JLabel();
        kembaliHompageButton = new javax.swing.JButton();
        pesanLagiButton = new javax.swing.JButton();
        idReservasiLabel = new javax.swing.JLabel();
        idReservasiIsiLabel = new javax.swing.JLabel();
        studioLabel = new javax.swing.JLabel();
        studioIsiLabel = new javax.swing.JLabel();
        navbarPanel = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));

        logoLabel.setFont(new java.awt.Font("Retro Majestic Free", 0, 18)); // NOI18N
        logoLabel.setText("Bonas Studio");

        judulLabel.setFont(new java.awt.Font("Poppins Medium", 0, 24)); // NOI18N
        judulLabel.setText("Buat Reservasi");

        isiLabel1.setFont(new java.awt.Font("Poppins", 0, 24)); // NOI18N
        isiLabel1.setText("Reservasi Anda telah diproses!");

        isiLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        isiLabel2.setText("Mohon melakukan pembayaran di kasir saat nanti.");

        totalBiayaLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        totalBiayaLabel.setText("Total Biaya:");

        totalBiayaIsiLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        totalBiayaIsiLabel.setText("Rp670.000");

        kembaliHompageButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        kembaliHompageButton.setText("Kembali ke Hompage");
        kembaliHompageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliHompageButtonActionPerformed(evt);
            }
        });

        pesanLagiButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        pesanLagiButton.setText("Pesan Lagi");
        pesanLagiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanLagiButtonActionPerformed(evt);
            }
        });

        idReservasiLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        idReservasiLabel.setText("ID Reservasi:");

        idReservasiIsiLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        idReservasiIsiLabel.setText("1");

        studioLabel.setFont(new java.awt.Font("Poppins SemiBold", 0, 14)); // NOI18N
        studioLabel.setText("Studio:");

        studioIsiLabel.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        studioIsiLabel.setText("1");

        javax.swing.GroupLayout bodyPanelLayout = new javax.swing.GroupLayout(bodyPanel);
        bodyPanel.setLayout(bodyPanelLayout);
        bodyPanelLayout.setHorizontalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoLabel)
                    .addComponent(isiLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isiLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(judulLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalBiayaIsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalBiayaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idReservasiIsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idReservasiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studioIsiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(290, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(kembaliHompageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesanLagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        bodyPanelLayout.setVerticalGroup(
            bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bodyPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(logoLabel)
                .addGap(0, 0, 0)
                .addComponent(judulLabel)
                .addGap(135, 135, 135)
                .addComponent(isiLabel1)
                .addGap(0, 0, 0)
                .addComponent(isiLabel2)
                .addGap(46, 46, 46)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(idReservasiLabel)
                        .addGap(0, 0, 0)
                        .addComponent(idReservasiIsiLabel))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(totalBiayaLabel)
                        .addGap(0, 0, 0)
                        .addComponent(totalBiayaIsiLabel))
                    .addGroup(bodyPanelLayout.createSequentialGroup()
                        .addComponent(studioLabel)
                        .addGap(0, 0, 0)
                        .addComponent(studioIsiLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(bodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesanLagiButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembaliHompageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        navbarPanel.setBackground(new java.awt.Color(102, 102, 102));

        backButton.setBackground(new java.awt.Color(102, 102, 102));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbarPanelLayout = new javax.swing.GroupLayout(navbarPanel);
        navbarPanel.setLayout(navbarPanelLayout);
        navbarPanelLayout.setHorizontalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        navbarPanelLayout.setVerticalGroup(
            navbarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbarPanelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(backButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(navbarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navbarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliHompageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliHompageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembaliHompageButtonActionPerformed

    private void pesanLagiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanLagiButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesanLagiButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatReservasiBayar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BuatReservasiBayar().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel idReservasiIsiLabel;
    private javax.swing.JLabel idReservasiLabel;
    private javax.swing.JLabel isiLabel1;
    private javax.swing.JLabel isiLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulLabel;
    private javax.swing.JButton kembaliHompageButton;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel navbarPanel;
    private javax.swing.JButton pesanLagiButton;
    private javax.swing.JLabel studioIsiLabel;
    private javax.swing.JLabel studioLabel;
    private javax.swing.JLabel totalBiayaIsiLabel;
    private javax.swing.JLabel totalBiayaLabel;
    // End of variables declaration//GEN-END:variables
}
